### ISSUE TITLE
April 2020: worked on a webmail and a bit of OpenSMTPD too

### ISSUE THREAD

**Issue by poolpOrg** [poolpOrg/poolp.org#76]

**Comment by cypa** [comment]
"I want to be able to read my mail from various places and not rely on a heavy client."
don't you see the web-browser is one of the heaviest clients ever?

**Comment by poolpOrg** [comment]
> "I want to be able to read my mail from various places and not rely on a heavy client."
> don't you see the web-browser is one of the heaviest clients ever?

https://en.wikipedia.org/wiki/Rich_client
