### ISSUE TITLE
February 2021: nooSMTPD libtls-conversion, ciphers, curves and protocols

### ISSUE THREAD

**Issue by poolpOrg** [poolpOrg/poolp.org#85]

**Comment by ArchangeGabriel** [comment]
Awesome indeed! Now it makes me wonder whether I should package nooSMPTD in Arch. ;p Quick answer: not now, no time for this (should first fix https://archlinux.org/packages/?sort=&q=&maintainer=Archange&flagged=Flagged —OK, that was much bigger than expected actually… :p), but I might give it a shot in July. ;)
